default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { '' } %>
  host: <%= ENV.fetch("DB_HOSTNAME") { '127.0.0.1' } %>
  port: <%= ENV.fetch("DB_PORT") { 3306 } %>
  database: <%= ENV.fetch("DB_DATABASENAME") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
